## Exercise 1

The next cell contains code to generate a DataFrame. The data is the number of cases of Tuberculosis (TB) in three countries over three years.

Add columns for the total and average number of cases over the three years.

In [1]:
import pandas as pd
df = pd.DataFrame(
    {
        '2011':[7000,5800,15000],
        '2012':[6900,6000,14000],
        '2013':[7000,6200,13000]
    },
    index=['France','Germany','United States of America']
)

df

                           2011   2012   2013
France                     7000   6900   7000
Germany                    5800   6000   6200
United States of America  15000  14000  13000

In [2]:
#adding over the rows

### 1b

What if we had a DataFrame with some missing or invalid entries?
The DataFrame below contains an entry ``pd.NA``, which is a special value in Pandas meaning 'not available'.
It stands in for data which is missing.

Having missing values could make it difficult to calculate a correct average. See if your method from part (a) still works. If it doesn't, then find a different way to calculate the average ignoring the missing value. For France the average should be $\frac{6900+7000}{2} = 6950$, but don't simply do this cacluation! Find a method which will work when you don't know how many of the values are 'not a number'.

In [3]:
df = pd.DataFrame(
    {
        '2011':[pd.NA,5800,15000],
        '2012':[6900,6000,14000],
        '2013':[7000,6200,13000]
    },
    index=['France','Germany','United States of America']
)

df

                           2011   2012   2013
France                     <NA>   6900   7000
Germany                    5800   6000   6200
United States of America  15000  14000  13000

In [4]:
# maybe add a total column?

### 1c

Finally, consider the possibility that the data you imported has some bad values in it. Here, for example, we know that the number of cases of TB can't be negative and must be a whole number. If any values are present which don't fit these criteria then we should highlight them. We might then choose to ignore these values in any calculations.

Create a function to check the quality of data in the DataFrame, replacing bad values with the special value ``pd.NA``. Then add columns for the sum and average of each row as before.

In [5]:
df = pd.DataFrame(
    {
        '2011':[pd.NA,5800,15000],
        '2012':[6900,60.3,14000],
        '2013':[7000,6200,-40]
    },
    index=['France','Germany','United States of America']
)

df

                           2011     2012  2013
France                     <NA>   6900.0  7000
Germany                    5800     60.3  6200
United States of America  15000  14000.0   -40

# Solutions to Exercises
## 1
### 1a
In the first part it is acceptable to manually calculate the sum and average for each column.

In [6]:
df = pd.DataFrame(
    {
        '2011':[7000,5800,15000],
        '2012':[6900,6000,14000],
        '2013':[7000,6200,13000]
    },
    index=['France','Germany','United States of America']
)

total = df['2011'] + df['2012'] + df['2013']
df.insert(value=total, column='total', loc=3)

average = round(total/3,1)
df.insert(value=average, column='average', loc=4)
df

                           2011   2012   2013  total  average
France                     7000   6900   7000  20900   6966.7
Germany                    5800   6000   6200  18000   6000.0
United States of America  15000  14000  13000  42000  14000.0

### 1b

Now we need to use the built in functions for finding the sum and average so that the ``pd.NA`` value is handled correctly.

In [7]:
df = pd.DataFrame(
    {
        '2011':[pd.NA,5800,15000],
        '2012':[6900,6000,14000],
        '2013':[7000,6200,13000]
    },
    index=['France','Germany','United States of America']
)

# axis=1 indicates we're finding the sum for each row, across multiple columns
# df.iloc selects the three columns we want to calculate the sum across (and all rows)
total = df.iloc[:, 0:3].sum(axis=1)
df.insert(value=total, column='total', loc=3)
df = df.astype('Int64')
# axis=1 indicates we're finding the mean for each row, across multiple columns
# df.iloc selects the three columns we want to calculate the mean across (and all rows)
average = round(df.iloc[:, 0:3].mean(axis=1),1)
df.insert(value=average, column='average', loc=4)
df

                           2011   2012   2013  total  average
France                     <NA>   6900   7000  13900   6950.0
Germany                    5800   6000   6200  18000   6000.0
United States of America  15000  14000  13000  42000  14000.0

### 1c

In this part we need to check for any value which is not a positive integer and remove this from the data before calculating the sum and average.

In [8]:
df = pd.DataFrame(
    {
        '2011':[pd.NA,5800,15000],
        '2012':[6900,60.3,14000],
        '2013':[7000,6200,-40]
    },
    index=['France','Germany','United States of America']
)

for col_name, data in df.items():
    for i, d in enumerate(data):
        if not d is pd.NA:
            if not int(d) == d or d < 0:
                df.at[df.index[i], col_name] = pd.NA

total = df.iloc[:, 0:3].sum(axis=1)
df.insert(value=total, column='total', loc=3)
df = df.astype('Int64')
average = round(df.iloc[:, 0:3].mean(axis=1),1)
df.insert(value=average, column='average', loc=4)
df

                           2011   2012  2013  total  average
France                     <NA>   6900  7000  13900   6950.0
Germany                    5800   <NA>  6200  12000   6000.0
United States of America  15000  14000  <NA>  29000  14500.0