# Manipulating DataFrames

In [1]:
import pandas as pd

## Exercise 1
Use the melt() function on the TB DataFrame and find the maximum number of infections in any single country in any single year.

In [2]:
df = pd.DataFrame(
    {
        'country': ['France','Germany','United States of America'],
        '2011':[7000,5800,15000],
        '2012':[6900,6000,14000],
        '2013':[7000,6200,13000]
    },
)

df

                    country   2011   2012   2013
0                    France   7000   6900   7000
1                   Germany   5800   6000   6200
2  United States of America  15000  14000  13000

## Exercise 2

Let us have a look at some data on the amount of pollution for different cities (New York, London and Beijing).

Pivot the DataFrame into the format

|city|large|small|
|---|---|---|
|Beijing| | |
|London| | |
|New York| | |

In [3]:
df_pollution = pd.DataFrame(
    {
        'size':['large','small','large','small','large','small'],
        'amount':[23,14,22,16,121,56]
    },
    index=['New York','New York','London','London','Beijing','Beijing']
)

df_pollution

           size  amount
New York  large      23
New York  small      14
London    large      22
London    small      16
Beijing   large     121
Beijing   small      56

# Solutions to Exercises
## 1

In [4]:
df = pd.DataFrame(
    {
        'country': ['France','Germany','United States of America'],
        '2011':[7000,5800,15000],
        '2012':[6900,6000,14000],
        '2013':[7000,6200,13000]
    },
)
df2 = pd.melt(df, id_vars='country', var_name='year', value_name='count')
df2['count'].max()

np.int64(15000)

## 2

In [5]:
import pandas as pd
df_pollution = pd.DataFrame(
    {
        'size':['large','small','large','small','large','small'],
        'amount':[23,14,22,16,121,56]
    },
    index=['New York','New York','London','London','Beijing','Beijing']
)

df_new = df_pollution.pivot(columns='size')
df_new.reset_index(inplace = True)
df_new.rename(columns = {"index":"city"}, inplace = True )

df_new

          city amount
size            large small
0      Beijing    121    56
1       London     22    16
2     New York     23    14